### ISSUE TITLE
Maven integration requires scalac-scapegoat-plugin as a dependency

### ISSUE THREAD

**Issue by tashoyan** [sksamuel/scapegoat#222]
We don't want to include scalac-scapegoat-plugin as a dependency of our product due to the following reasons:
* scalac-scapegoat-plugin comes to the product package but is not acutally used by the product
   * to avoid this issue, we have to put special inclusions in the assembly descriptor
* we have checks for unused dependencies by maven-dependency-plugin and these checks fail due to scalac-scapegoat-plugin
   * to avoid this issue, we have to put a special exclusion to the configuration of maven-dependency-plugin

I tried to include scalac-scapegoat-plugin as a **dependency of scala-maven-plugin** rather than of the product itself, but this does not work:
```
[ERROR] error: scala.ScalaReflectionException: object com.sksamuel.scapegoat.Safe in compiler mirror not found.
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:129)
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:29)
...
```

**Comment by joshrosen-stripe** [comment]
I have the same problem. There's an earlier report of this issue in #98.

Based on the fix for a similar problem in #163, plus the fact that putting Scapegoat as a dependency of your project resolves this problem, my best guess is that this problem is caused by `typeOf[X]` where `X` references a type that is not on the project's compile classpath. In this case, it's failing because `com.sksamuel.scapegoat.Safe` is not on the compiler classpath; in #163 the problem was caused by an existential type in Scapegoat being missing from the path.

We may be able to work around this by modifying the code using `typeOf[Safe]` to instead compare class name strings, removing the runtime dependency.
