### ISSUE TITLE
[false positive] Method name not recommended

### ISSUE THREAD

**Issue by wlk** [sksamuel/scapegoat#271]
I'm stumbling on "Method name not recommended" warning in following code (simplified example)

```
case class Amount(amount: BigDecimal) {
  def unary_- = Amount(-amount)
}
```

can you confirm if this is a false positive?

I have seen this being reported earlier in https://github.com/sksamuel/scapegoat/issues/148 but I'm using latest versions of scapegoat: 
```
scapegoatVersion in ThisBuild := "1.4.1"
...
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.1.0")
```

**Comment by mccartney** [comment]
I don't see it being fixed in https://github.com/sksamuel/scapegoat/blob/master/src/main/scala/com/sksamuel/scapegoat/inspections/naming/MethodNames.scala
I can only see the regexp allows for optional trailing `_` which I *guess* was the (partial) fix. Your case is similar but not the same as presented in #148 (they wanted an assignment operator, you have the unary minus `-`).
Let's fix it.

**Comment by wlk** [comment]
Thank you :)
